import { Cenario, Icon, LetterTile } from './menu';
import { ResultHeading, PanelMedallion } from './acabamentos';
import { HudIcon, VidasHud } from './icones-hud';

function Hud(): string {
  return `<div class="jg-hud" role="status" aria-label="Estatísticas da partida">${[
    ['azul','PONTOS','<strong id="pontos" data-testid="hud-score-value">0</strong>',HudIcon('pontos')],
    ['verde','COMBO','<strong id="combo" data-testid="hud-combo-multiplier">×0</strong>',HudIcon('combo')],
    ['rosa','VIDAS',`<strong id="vidas" data-testid="hud-lives-display" aria-label="3 vidas">${VidasHud(3)}</strong>`,''],
    ['ciano','CALOR','<strong id="heat-texto" data-testid="hud-heat-value">0%</strong><span class="jg-heat" aria-hidden="true"><i id="heat-barra"></i></span>',HudIcon('calor')],
  ].map(([cor,label,body,icon])=>`<span class="jg-marcador ${cor}" data-testid="hud-card-${cor}"><span class="jg-marcador-topo">${icon?`<i class="jg-marcador-icone" aria-hidden="true">${icon}</i>`:''}<small data-testid="hud-label-${cor}">${label}</small></span><span class="jg-marcador-corpo">${body}</span></span>`).join('')}</div>`;
}

function Cartao(): string {
  return `<div class="jg-tempo-linha"><i class="nw-faisca f1"></i><div class="jg-tempo" aria-label="Tempo restante"><i id="barra-tempo" data-testid="timer-progress"></i><span class="jg-tempo-corpo">${Icon({nome:'relogio'})}<b id="tempo-numero" data-testid="timer-value">10s</b></span></div><i class="nw-faisca f2"></i></div><p class="jg-evento"><span id="evento-ronda">RONDA NORMAL</span></p>
  <section class="nw-card gold jg-card" data-testid="question-card"><span class="nw-card-topo"><span class="nw-chip numero" id="numero-pergunta">01</span><span class="nw-chip nome" id="modo-etiqueta">PLURAL</span><span class="nw-chip" id="nivel-jogo">NV. 01</span></span>
    <span class="nw-arte pilha" aria-hidden="true"><i class="nw-faisca f1"></i><i class="nw-faisca f2"></i><i class="nw-faisca f3"></i>${LetterTile('R','blue','t1')}${LetterTile('A','pink','t2')}${LetterTile('A','yellow','t3')}</span>
    <div class="jg-bloco"><div class="jg-pergunta"><h1 id="palavra" data-testid="question-word">ÁRVORE</h1><p id="instrucao">Escreve o plural</p></div><div class="jg-resposta" id="resposta-wrap"><input id="resposta" data-testid="gameplay-answer-input" type="text" autocomplete="off" autocapitalize="none" spellcheck="false" enterkeyhint="done" maxlength="32" placeholder="escreve aqui…" aria-label="Resposta"/><label for="resposta" id="estado-input">A TUA RESPOSTA</label></div></div>
    <div class="jg-accoes"><button class="nw-cta jg-confirmar" id="confirmar" data-testid="gameplay-confirm-button"><strong>CONFIRMAR</strong><i>${Icon({nome:'play'})}</i></button><button class="nw-cta cinza jg-pular" id="pular" data-testid="gameplay-skip-button" aria-label="Saltar palavra e perder uma vida"><strong>SALTAR</strong><i>${Icon({nome:'saltar'})}</i></button></div>
    <div class="jg-pausa-aviso" id="pausa-card" data-testid="game-pause-panel" hidden><span class="pausa-medalhao" aria-hidden="true">${Icon({nome:'pausa'})}</span><strong data-testid="game-pause-title">Uma pausa.</strong><p data-testid="game-pause-description">O relógio espera por ti.</p><button class="nw-cta" id="retomar-card" data-testid="gameplay-resume-button"><strong>CONTINUAR</strong><i>${Icon({nome:'play'})}</i></button></div>
  </section>`;
}

function Faixas(): string {
  return `<div class="jg-faixa roxa" id="record-comparison-card" data-testid="record-comparison-card">${PanelMedallion('record')}<span class="jg-faixa-corpo"><small>RITMO DO RECORDE</small><b id="fantasma-recorde">PRIMEIRO PERCURSO</b><span class="jg-barra"><i id="fantasma-barra"></i></span><span class="record-empty-caption" id="record-empty-caption" data-testid="record-empty-caption">A tua primeira marca começa aqui.</span></span></div><div class="jg-faixa azul" data-testid="recent-answers-card">${PanelMedallion('history')}<span class="jg-faixa-corpo"><small>ÚLTIMAS RESPOSTAS</small><div class="jg-historico" id="historico" aria-label="Respostas anteriores"></div></span></div>
  <nav class="nw-bottom jg-bottom" aria-label="Controlos"><button id="pausa" data-testid="gameplay-pause-button"><span class="nw-nav-icone">${Icon({nome:'pausa'})}</span><b id="pausa-texto">PAUSAR</b></button><i class="nw-divisoria"></i><button id="som" data-testid="gameplay-sound-button" aria-pressed="true"><span class="nw-nav-icone">${Icon({nome:'som',classe:'icone-som'})}${Icon({nome:'sem-som',classe:'icone-mudo'})}</span><b id="som-texto">SOM</b></button><i class="nw-divisoria"></i><button id="voltar" data-testid="gameplay-back-button"><span class="nw-nav-icone">${Icon({nome:'sair'})}</span><b>SAIR</b></button></nav>`;
}

function Paineis(): string {
  return `<div class="jg-feedback" id="feedback" role="status" hidden><strong id="feedback-titulo">CERTO</strong><span id="feedback-texto" data-testid="feedback-text">+145 PONTOS</span></div><div class="jg-contagem" id="contagem" hidden><small id="contagem-modo">PLURAL</small><span>PREPARA-TE</span><b id="contagem-numero">3</b><p data-testid="countdown-caption">Uma palavra de cada vez.</p></div>
  <section class="jg-painel" id="painel" data-testid="results-dialog" role="dialog" aria-modal="true" aria-labelledby="result-title" hidden><div class="jg-painel-caixa">${ResultHeading()}<div class="result-score"><h2 id="painel-titulo" data-testid="results-score">0</h2><small data-testid="results-score-label">PONTOS</small></div><p id="painel-texto" data-testid="results-record">NOVO RECORDE</p><p class="result-encouragement" id="resultado-frase" data-testid="results-encouragement">Cada palavra conta.</p><div class="jg-medalha" id="medalha-perfeita" hidden>${Icon({nome:'trophy'})} PERFECT RUN</div><div class="jg-resumo">${[['certas','CERTAS'],['erradas','ERRADAS'],['combo','MELHOR COMBO'],['tempo','TEMPO MÉDIO']].map(([id,label])=>`<span class="summary-${id}"><b id="resumo-${id}">0</b><small>${label}</small></span>`).join('')}</div><button class="nw-cta jg-painel-cta" id="jogar-novamente" data-testid="play-again-button"><strong>JOGAR OUTRA VEZ</strong><i>${Icon({nome:'play'})}</i></button><div class="jg-painel-linha"><button class="jg-botao-claro" id="rever-erros" data-testid="review-errors-button">${Icon({nome:'balao'})}<b>REVER ERROS</b></button><button class="jg-botao-claro" id="ir-menu" data-testid="results-menu-button">${Icon({nome:'sair'})}<b>OUTRO MODO</b></button></div></div></section>
  <section class="jg-revisao" id="revisao" data-testid="review-dialog" role="dialog" aria-modal="true" aria-labelledby="review-title" hidden><div class="jg-revisao-caixa"><header><button id="fechar-revisao" data-testid="review-close" aria-label="Fechar revisão">${Icon({nome:'chevron',classe:'voltar'})}</button><span><small>APRENDER TAMBÉM É JOGAR</small><h2 id="review-title">Palavras a rever</h2></span></header><p class="review-intro" data-testid="review-intro">Um olhar à resposta. Mais uma palavra para a próxima.</p><div id="lista-erros"></div></div></section>`;
}

export function montarJogo(raiz: HTMLElement): void {
  raiz.dataset.testid='game-screen';
  raiz.innerHTML=`${Cenario()}<header class="nw-top"><span class="nw-marca"><i>N</i><b>NEXUS WORD</b></span><span class="nw-streak">${Icon({nome:'flame'})}<b id="dias-jogo">1</b> DIA</span></header>${Hud()}${Cartao()}${Faixas()}<p class="nw-motto" data-testid="game-motto">PENSA <i></i> JOGA <i></i> APRENDE</p>${Paineis()}`;
}