import type { Modo } from './dados';

type Icone='flame'|'crown'|'play'|'swap'|'calendar'|'trophy'|'chart'|'settings'|'arrow';
const paths:Record<Icone,string>={
  flame:'<path d="M12 2c1 4-1 5 2 8 1-2 3-3 3-6 4 4 5 8 3 13a8 8 0 1 1-15-5c1-3 3-5 5-7 0 3 0 5 2 6 2-3 1-6 0-9Z"/><path d="M12 13c2 2 3 4 1 7-4 0-5-4-1-7Z" class="detail"/>',
  crown:'<path d="m3 7 4 4 5-7 5 7 4-4-2 11H5L3 7Z"/><path d="M6 21h12" class="line"/>',
  play:'<path d="m9 6 9 6-9 6V6Z"/>',
  swap:'<path d="M4 8h13l-3-3m3 3-3 3M20 16H7l3 3m-3-3 3-3" class="line"/>',
  calendar:'<rect x="3" y="5" width="18" height="16" rx="3" class="line"/><path d="M7 3v5m10-5v5M3 10h18M8 14h3m2 0h3m-8 3h3" class="line"/>',
  trophy:'<path d="M8 4h8v5c0 4-2 6-4 6s-4-2-4-6V4Zm0 2H4v2c0 3 2 4 5 4m7-6h4v2c0 3-2 4-5 4M12 15v4m-4 2h8"/>',
  chart:'<path d="M4 20V11h4v9H4Zm6 0V4h4v16h-4Zm6 0v-6h4v6h-4Z"/>',
  settings:'<path d="M9.6 3h4.8l.7 2.2 2 .8 2.1-1 2.4 4.1-1.7 1.5v2.8l1.7 1.5-2.4 4.1-2.1-1-2 .8-.7 2.2H9.6l-.7-2.2-2-.8-2.1 1-2.4-4.1 1.7-1.5v-2.8L2.4 9.1 4.8 5l2.1 1 2-.8L9.6 3Z"/><circle cx="12" cy="12" r="3" class="cut"/>',
  arrow:'<path d="M6 12h12m-5-5 5 5-5 5" class="line"/>',
};
export function Icon({nome,classe=''}:{nome:Icone;classe?:string}):string{return `<svg class="nw-icon ${classe}" viewBox="0 0 24 24" aria-hidden="true">${paths[nome]}</svg>`;}
export function LetterTile(letra:string,cor:'green'|'pink'|'blue'|'yellow',classe=''):string{return `<span class="nw-letter ${cor} ${classe}" aria-hidden="true"><i></i><b>${letra}</b></span>`;}
interface ModeDef{modo:Modo;numero:string;nome:string;origem:string;destino:string;descricao:string;cor:string}
const modos:ModeDef[]=[
  {modo:'plural',numero:'01',nome:'PLURAL',origem:'ÁRVORE',destino:'ÁRVORES',descricao:'Uma torna-se várias',cor:'gold'},
  {modo:'singular',numero:'02',nome:'SINGULAR',origem:'LIMÕES',destino:'LIMÃO',descricao:'Várias tornam-se uma',cor:'green'},
  {modo:'contrario',numero:'03',nome:'CONTRÁRIO',origem:'GANHAR',destino:'PERDER',descricao:'Encontra o oposto',cor:'pink'},
];
export function GameButton(compacto=false):string{return `<span class="nw-play ${compacto?'compacto':''}"><strong>${compacto?'': 'JOGAR'}</strong>${Icon({nome:'play'})}</span>`;}
export function ModeCard(d:ModeDef,principal=false):string{const icon=d.modo==='plural'?`<span class="tile-stack">${LetterTile('A','blue')}${LetterTile('R','pink')}${LetterTile('A','yellow')}</span>`:d.modo==='singular'?`<span class="mode-art singular-art">${LetterTile('S','green')}<i class="lime"></i></span>`:`<span class="mode-art contrario-art">${Icon({nome:'swap'})}</span>`;return `<button type="button" class="nw-mode-card ${d.cor} ${principal?'principal seleccionado':'secundario'}" data-modo="${d.modo}" role="listitem" aria-label="Jogar ${d.nome}"><span class="nw-number">${d.numero}</span><span class="nw-level">LV. 01</span><span class="nw-mode-name">${d.nome}</span>${icon}<span class="nw-mode-copy"><span class="exemplo"><b data-exemplo-origem>${d.origem}</b><em>${d.modo==='contrario'?'↔':'→'}</em><b data-exemplo-destino>${d.destino}</b></span><small>${d.descricao}</small><span class="recorde-menu" data-recorde="${d.modo}">MELHOR COMBO —</span></span>${GameButton(!principal)}</button>`;}
export function StatCard():string{return `<section class="nw-best"><span class="best-crown">${Icon({nome:'crown'})}</span><strong>MELHOR SEQUÊNCIA</strong><b id="melhor-sequencia">0</b></section>`;}
export function DailyWordCard():string{return `<button class="nw-daily word" id="ver-palavra-dia" type="button"><span class="daily-icon">${Icon({nome:'calendar'})}</span><span><small>PALAVRA DO DIA</small><b id="palavra-dia">LACÓNICO</b><em id="significado-dia">expressão em poucas palavras</em></span><i>${Icon({nome:'arrow'})}</i></button>`;}
export function DailyChallengeCard():string{return `<button class="nw-daily challenge" id="abrir-desafio-dia" type="button"><span class="daily-icon">${Icon({nome:'trophy'})}</span><span><small>DESAFIO DO DIA</small><b>15 respostas seguidas</b><span class="challenge-progress"><i><em id="desafio-barra"></em></i><strong id="desafio-valor">0 / 15</strong></span></span><i>${Icon({nome:'arrow'})}</i></button>`;}
export function BottomNavigation():string{return `<nav class="nw-bottom" aria-label="Navegação"><button id="abrir-recordes" type="button">${Icon({nome:'chart'})}<b>RECORDES</b>${Icon({nome:'arrow',classe:'chevron'})}</button><i></i><button id="abrir-definicoes" type="button">${Icon({nome:'settings'})}<b>DEFINIÇÕES</b>${Icon({nome:'arrow',classe:'chevron'})}</button></nav>`;}
export function montarMenu(raiz:HTMLElement):void{raiz.innerHTML=`<div class="nw-scene" aria-hidden="true"><i class="cloud c1"></i><i class="cloud c2"></i><i class="hill h1"></i><i class="hill h2"></i><i class="bush b1"></i><i class="bush b2"></i><i class="flower f1"></i><i class="flower f2"></i></div><header class="nw-top"><span class="nw-brand"><i>N</i><b>NEXUS WORD</b></span><span class="nw-streak">${Icon({nome:'flame'})}<b id="dias">1</b> DIA</span></header><section class="nw-hero"><div class="hero-tiles">${LetterTile('P','green','p')}${LetterTile('R','pink','r')}${LetterTile('S','blue','s')}${LetterTile('A','yellow','a')}</div><h1 id="titulo-menu"><span>NEXUS</span><b>WORD</b></h1><p>PALAVRAS. RAPIDEZ.</p></section>${StatCard()}<section class="modos" role="list" aria-label="Modos de jogo">${ModeCard(modos[0],true)}<div class="secondary-row">${ModeCard(modos[1])}${ModeCard(modos[2])}</div></section><section class="nw-dailies">${DailyWordCard()}${DailyChallengeCard()}</section>${BottomNavigation()}<p class="nw-motto">PENSA <i></i> CLICA <i></i> APRENDE</p><section class="folha" id="folha" hidden><button class="folha-fundo" id="fechar-folha" aria-label="Fechar"></button><div class="folha-painel"><i></i><header><span><small id="folha-etiqueta">NEXUS WORD</small><h2 id="folha-titulo">Recordes</h2></span><button id="fechar-folha-x" type="button">×</button></header><div id="folha-conteudo"></div></div></section>`;}
